# This is a basic workflow to help you get started with Actions
# for running post man colllection using newman with selected env

name: "Newman Tests"
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    container: 
      image: postman/newman
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Run API Tests
        run: newman run "Restful Booker BVT.postman_collection.json" -e Production.postman_environment.json  
        # --env-var "password=1542" to specify env varaible in collection run 
 
        
